services:
  minio:
    image: minio/minio:latest
    container_name: local-s3
    ports:
      - "9000:9000"   # S3 API port
      - "9001:9001"   # Web UI port
    environment:
      MINIO_ROOT_USER: minioadmin  # Set your access key
      MINIO_ROOT_PASSWORD: minioadmin  # Set your secret key
    volumes:
      - ./local_data:/data  # Persistent storage
    command: server /data --console-address ":9001"


