services:
  minio:
    image: minio/minio:latest
    container_name: local-s3
    ports:
      - "9000:9000"   # S3 API port
      - "9001:9001"   # Web UI port
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: localpassword
    volumes:
      - ./local_data/s3:/data
    command: server /data --console-address ":9001"

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: localpassword
      POSTGRES_DB: openalex
    ports:
      - "5432:5432"
    volumes:
      - ./local_data/postgres:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres
